# このファイルでCodeBuildのビルド処理を規定する

version: 0.2

phases:
  # 使用するDockerのランタイムバージョン
  install:
    runtime-versions:
      docker: 18
  # ECRにログイン
  pre_build:
    commands:
    - $(aws ecr get-login --region ap-northeast-1 --no-include-email)
        - REPO=$(aws ecr describe-repositories --repository-names ecr-repository --output text --query "repositories[0].repositoryUri")
    - IMAGE=$REPO:v2
  # Dockerイメージのビルドとプッシュ
  build:
    commands:
    - docker build -t $IMAGE .
    - docker push $IMAGE
  # 「imagedefinitions.json」ファイルの作成
  post_build:
    commands:
    - printf '[{"name":"ecr-repository","imageUri":"%s"}]' $IMAGE > imagedefinitions.json
artifacts:
  files: imagedefinitions.json